CREATE TABLE IF NOT EXISTS "User" (
	user_id SERIAL PRIMARY KEY,
	email VARCHAR(100) UNIQUE NOT NULL,
	passhash VARCHAR(500) NOT NULL,
	user_name VARCHAR(100) NOT NULL,
	verified BOOLEAN DEFAULT FALSE NOT NULL,
	created_at TIMESTAMP DEFAULT NULL
);

ALTER TABLE "User" ALTER COLUMN created_at SET DEFAULT NOW();
